import type { Metadata } from "next";
import "./globals.css";
import { Inter, Rubik } from "next/font/google";
import {ModalProvider} from "@/contexts/modal-context";
import {ClientAuthProvider} from "@/contexts/auth-provider";
import LoginModal from "@/components/modals/LoginModal";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-inter',
  display: 'swap',
});

const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-rubik',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Zen Moda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${rubik.variable} antialiased`}
      >
      <ClientAuthProvider>
        <ModalProvider>
          {children}
          <LoginModal />
        </ModalProvider>
      </ClientAuthProvider>
      </body>
    </html>
  );
}
